Repository drupal-composer/drupal-project, pull requests merged in 2024-05, with the labels that each got.

#643 Fixed SQLite version in CI.
  .github/workflows/ci.yml
Labels: bug, D11

#551 Update ScriptHandler.php to check for symlinks before creating files directory
  scripts/composer/ScriptHandler.php
Labels: PR: Requires more work

#648 [#462] Removed PHP version from `composer.json`.
  README.md
  composer.json
Labels: D10, PR: Needs review

#651 [#647] Added Composer normalizer.
  composer.json
Labels: D10, PR: Needs review

#652 [#647] Added Composer normalizer.
  composer.json
Labels: D11, PR: Needs review

#654 [10.x] Re-formatted CI and added more PHP versions to the test matrix.
  .github/workflows/ci.yml
Labels: D10, PR: Do not review

#655 [11.x] Re-formatted CI and added more PHP versions to the test matrix.
  .github/workflows/ci.yml
Labels: D11, PR: Needs review

#656 [10.x] Updated readme.
  README.md
Labels: D10, PR: Needs review

#657 [11.x] Updated readme.
  README.md
Labels: D11, PR: Needs review

#658 [#653] Added Composer normalizer check to CI.
  .github/workflows/ci.yml
Labels: D10, PR: Needs review

#659 [#653] Added Composer normalizer check to CI.
  .github/workflows/ci.yml
Labels: D11, PR: Needs review

#662 [#660] Fixed required Composer version constraint and added a CI job.
  .github/workflows/ci.yml
  scripts/composer/ScriptHandler.php
Labels: D10, PR: Needs review

#663 [#278] Added support for Asset packagist.
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: D10, PR: Needs review

#664 [#660] Fixed required Composer version constraint and added a CI job.
  .github/workflows/ci.yml
  scripts/composer/ScriptHandler.php
Labels: D11, PR: Needs review

#665 [#278] Added support for Asset packagist.
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: D11, PR: Needs review

#666 [#266] Set `minimum-stability` to `true` and added docs.
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: D10, PR: Needs review

#667 [#266] Set `minimum-stability` to `stable` and added docs.
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: D11, PR: Needs review

#669 [#646] Added installer paths for custom modules, profiles and themes.
  composer.json
Labels: D11, PR: Needs review

#668 [#646] Added installer paths for custom modules, profiles and themes.
  composer.json
Labels: D10, PR: Needs review

#670 Added site information to CI.
  .github/workflows/ci.yml
Labels: D10, PR: Needs review
